#!/usr/bin/env node
// Generates Rust FFI stubs from bloom's package.json manifest.
// Output: src/ffi_stubs.rs — all bloom_* functions as #[no_mangle] stubs.
// Functions implemented elsewhere in lib.rs (the override list) are skipped.

const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'package.json'), 'utf8'));
const fns = pkg.perry.nativeLibrary.functions;

const OVERRIDES = new Set([
  'bloom_get_platform',
  'bloom_get_crown_rotation',
  'bloom_get_screen_width',
  'bloom_get_screen_height',
  'bloom_get_touch_x',
  'bloom_get_touch_y',
  'bloom_get_touch_count',
  'bloom_get_delta_time',
  'bloom_get_time',
  'bloom_get_fps',
  'bloom_init_window',
  'bloom_close_window',
  'bloom_window_should_close',
  'bloom_begin_drawing',
  'bloom_end_drawing',
  'bloom_clear_background',
  'bloom_run_game',
  'bloom_is_any_input_pressed',
  'bloom_is_key_pressed',
  'bloom_is_key_down',
  'bloom_is_key_released',
  'bloom_set_target_fps',
  'bloom_inject_key_down',
  'bloom_inject_key_up',
  'bloom_inject_gamepad_axis',
  'bloom_inject_gamepad_button_down',
  'bloom_inject_gamepad_button_up',
  'bloom_is_gamepad_available',
  'bloom_get_gamepad_axis',
  'bloom_is_gamepad_button_pressed',
  'bloom_is_gamepad_button_down',
  'bloom_is_gamepad_button_released',
  'bloom_get_gamepad_axis_count',
]);

const rustType = (p) => {
  if (p === 'f64') return 'f64';
  if (p === 'i64') return 'i64';
  if (p === 'void') return '()';
  throw new Error(`Unknown param type: ${p}`);
};

const defaultForReturn = (r) => {
  if (r === 'f64') return '0.0';
  if (r === 'i64') return '0';
  if (r === 'void') return '()';
  throw new Error(`Unknown return type: ${r}`);
};

let out = '// Auto-generated by gen_stubs.js — do not edit by hand.\n';
out += '// All non-overridden bloom_* FFI functions as no-op stubs.\n';
out += '// The watchOS proof-of-life crate implements only the input / platform\n';
out += '// surface; rendering calls are intentionally no-ops pending the wgpu/Metal\n';
out += '// dlopen work.\n\n';
out += '#![allow(unused_variables, non_snake_case)]\n\n';

let skipped = 0;
for (const fn of fns) {
  if (OVERRIDES.has(fn.name)) { skipped++; continue; }
  const params = fn.params.map((p, i) => `_p${i}: ${rustType(p)}`).join(', ');
  const ret = fn.returns === 'void' ? '' : ` -> ${rustType(fn.returns)}`;
  const body = fn.returns === 'void' ? '' : `    ${defaultForReturn(fn.returns)}\n`;
  out += `#[no_mangle] pub extern "C" fn ${fn.name}(${params})${ret} {\n${body}}\n`;
}

fs.writeFileSync(path.join(__dirname, 'src', 'ffi_stubs.rs'), out);
console.error(`Wrote ${fns.length - skipped} stubs to src/ffi_stubs.rs (skipped ${skipped} overrides)`);
