// Auto-generated by gen_stubs.js — do not edit by hand.
// All non-overridden bloom_* FFI functions as no-op stubs.
// The watchOS proof-of-life crate implements only the input / platform
// surface; rendering calls are intentionally no-ops pending the wgpu/Metal
// dlopen work.

#![allow(unused_variables, non_snake_case)]

#[no_mangle] pub extern "C" fn bloom_take_screenshot(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_set_env_clear_from_hdr(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_is_mouse_button_pressed(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_is_mouse_button_down(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_is_mouse_button_released(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_init_audio() {
}
#[no_mangle] pub extern "C" fn bloom_close_audio() {
}
#[no_mangle] pub extern "C" fn bloom_load_sound(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_play_sound(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_stop_sound(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sound_volume(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_master_volume(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_play_sound_3d(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_listener_position(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_load_image(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_image_resize(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_image_crop(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_image_flip_h(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_image_flip_v(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_load_texture_from_image(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_gen_texture_mipmaps(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_begin_mode_2d(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_end_mode_2d() {
}
#[no_mangle] pub extern "C" fn bloom_draw_ray(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64, _p9: f64) {
}
#[no_mangle] pub extern "C" fn bloom_load_model(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_draw_model(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64, _p8: f64) {
}
#[no_mangle] pub extern "C" fn bloom_unload_model(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_gen_mesh_cube(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_gen_mesh_heightmap(_p0: f64, _p1: f64, _p2: f64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_load_shader(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_load_model_animation(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_update_model_animation(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_create_mesh(_p0: i64, _p1: f64, _p2: i64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_joint_test(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ambient_light(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_directional_light(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_fog(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_chromatic_aberration(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_vignette(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_film_grain(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sun_shafts(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_auto_exposure(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_taa_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_manual_exposure(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_env_intensity(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssgi_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssgi_intensity(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssgi_radius(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_dof(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_quality_preset(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_shadows_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_bloom_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssao_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_ssr_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_motion_blur_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_sss_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_profiler_enabled(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_get_profiler_frame_cpu_us() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_profiler_frame_gpu_us() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_print_profiler_summary() {
}
#[no_mangle] pub extern "C" fn bloom_get_model_mesh_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_material_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_load_music(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_play_music(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_stop_music(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_update_music_stream(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_music_volume(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_is_music_playing(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_toggle_fullscreen() {
}
#[no_mangle] pub extern "C" fn bloom_set_window_title(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_set_window_icon(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_disable_cursor() {
}
#[no_mangle] pub extern "C" fn bloom_enable_cursor() {
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_delta_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_delta_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_mouse_wheel() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_char_pressed() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_min_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_min_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_min_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_max_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_max_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_get_model_bounds_max_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_register_frame_callback(_p0: f64, _p1: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_unregister_frame_callback(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_add_directional_light(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_add_point_light(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_create_node() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_destroy_node(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_visible(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_cast_shadow(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_receive_shadow(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_parent(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_transform(_p0: f64, _p1: i64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_update_geometry(_p0: f64, _p1: i64, _p2: f64, _p3: i64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_material_color(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_material_pbr(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_set_material_texture(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_node_count() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_node_vertex_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_node_index_count(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_set_cursor_shape(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_set_clipboard_text(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_get_clipboard_text() -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_open_file_dialog(_p0: i64, _p1: i64) -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_save_file_dialog(_p0: i64, _p1: i64) -> i64 {
    0
}
#[no_mangle] pub extern "C" fn bloom_scene_pick_all(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_all_handle(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_all_distance(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_set_material_water(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_gen_mesh_spline_ribbon(_p0: i64, _p1: f64, _p2: i64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_load_render_texture(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_unload_render_texture(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_begin_texture_mode(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_end_texture_mode() {
}
#[no_mangle] pub extern "C" fn bloom_get_render_texture_texture(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_transform(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_min_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_min_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_min_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_max_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_max_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_get_bounds_max_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_set_user_data(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_get_user_data(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_extrude_polygon(_p0: f64, _p1: i64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_subtract_box(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) {
}
#[no_mangle] pub extern "C" fn bloom_enable_shadows() {
}
#[no_mangle] pub extern "C" fn bloom_disable_shadows() {
}
#[no_mangle] pub extern "C" fn bloom_dump_shadow_map(_p0: i64) {
}
#[no_mangle] pub extern "C" fn bloom_scene_attach_model(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_enable_postfx() {
}
#[no_mangle] pub extern "C" fn bloom_disable_postfx() {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_selected(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_hovered(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_outline_color(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_postfx_set_outline_thickness(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_project_to_screen(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_project_screen_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_scene_pick(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_handle() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_distance() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_z() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_normal_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_normal_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_pick_hit_normal_z() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_stage_texture(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_stage_model(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_stage_sound(_p0: i64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_texture(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_model(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_sound(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_commit_music(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_create_world(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_gravity(_p0: f64, _p1: f64, _p2: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_timestep(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_create_body(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_destroy_body(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_body_enabled(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_body_ccd(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_body_gravity_scale(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_kinematic_target(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_lock_rotations(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_add_box_collider(_p0: f64, _p1: f64, _p2: f64, _p3: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_add_sphere_collider(_p0: f64, _p1: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_add_capsule_collider(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_add_cylinder_collider(_p0: f64, _p1: f64, _p2: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_set_collider_properties(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_apply_force(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_apply_impulse(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_apply_torque(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_apply_torque_impulse(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_linear_velocity(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_set_angular_velocity(_p0: f64, _p1: f64, _p2: f64, _p3: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_step(_p0: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_sync_transforms() {
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_position_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_position_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_position_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_rotation_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_rotation_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_rotation_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_body_rotation_w(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_linear_velocity_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_linear_velocity_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_linear_velocity_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_angular_velocity_x(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_angular_velocity_y(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_angular_velocity_z(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_raycast(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_body() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_distance() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_x() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_y() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_ray_hit_z() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_collision_count() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_collision_event(_p0: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_collision_body_b() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_get_collision_started() -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_attach_scene_node(_p0: f64, _p1: f64) {
}
#[no_mangle] pub extern "C" fn bloom_physics_create_fixed_joint(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_create_revolute_joint(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_create_prismatic_joint(_p0: f64, _p1: f64, _p2: f64, _p3: f64, _p4: f64, _p5: f64, _p6: f64, _p7: f64) -> f64 {
    0.0
}
#[no_mangle] pub extern "C" fn bloom_physics_destroy_joint(_p0: f64) {
}
