

// Shader sources are grouped by pass cluster (2000-line file policy);
// everything re-exports from here so call sites keep `shaders::NAME`.

mod core;
pub(super) use core::{SHADER_2D, SHADER_3D, SCENE_SHADER};
mod env;
pub(super) use env::{PREFILTER_SHADER_WGSL, SKY_SHADER_WGSL, AERIAL_PERSPECTIVE_SHADER_WGSL, SKY_VIEW_LUT_SHADER_WGSL, EQUIRECT_FROM_SKY_VIEW_SHADER_WGSL, PROCEDURAL_SKY_SHADER_WGSL, REFLECT_SCENE_WGSL};
mod ao;
pub(super) use ao::{HIZ_LINEARIZE_SHADER_WGSL, HIZ_DOWNSAMPLE_SHADER_WGSL, SSAO_SHADER_WGSL, SSAO_BLUR_SHADER_WGSL};
mod gi;
pub(super) use gi::{CARD_CAPTURE_WGSL, SDF_BAKE_WGSL, SDF_CLIPMAP_BAKE_WGSL, CARD_LIGHT_WGSL, WSRC_BAKE_WGSL, WSRC_BAKE_HW_WGSL};
mod ssgi;
pub(super) use ssgi::{PROBE_HELPERS_WGSL, SSGI_PROBE_PLACE_WGSL, SSGI_PROBE_TRACE_SW_WGSL, SSGI_PROBE_TRACE_HW_WGSL, SSGI_PROBE_TRACE_SDF_WGSL, SSGI_PROBE_TEMPORAL_WGSL, SSGI_PROBE_RESOLVE_WGSL, SSR_TEMPORAL_SHADER_WGSL, SSR_SHADER_WGSL};
mod pt;
pub(super) use pt::{PT_KERNEL_WGSL, PT_ATROUS_WGSL};
mod post;
pub(super) use post::{BLOOM_SHADER_WGSL, DOF_SHADER_WGSL, MOTION_BLUR_SHADER_WGSL, SSS_SHADER_WGSL, SCENE_COMPOSE_SHADER_WGSL, TAA_SHADER_WGSL, EXPOSURE_SHADER_WGSL, COMPOSITE_SHADER_WGSL, UPSCALE_SHADER_WGSL, RCAS_SHADER_WGSL};
