#!/usr/bin/env node
// validate-ffi.js — cross-checks the FFI surface three ways:
//
//   package.json (perry.nativeLibrary.functions)   ← what Perry codegen emits
//   native/shared/src/ffi_core.rs + physics_jolt.rs ← what the macros generate
//   native/<platform>/src/*.rs                      ← what each crate hand-writes
//
// Fails (exit 1) when:
//   - a manifest function is not exported by some platform
//   - an exported function's arity disagrees with the manifest
//   - a platform hand-writes a function the shared macros already generate
//     (duplicate symbol at link time)
//
// Warns when a platform exports a bloom_* function the manifest doesn't
// declare (unreachable from TypeScript) unless it is allowlisted below.
//
// Run: node tools/validate-ffi.js        (CI runs this on every push)
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PLATFORMS = ['macos', 'linux', 'windows', 'android', 'ios', 'tvos', 'watchos'];

// Exported on purpose but not (yet) declared in the manifest — native-side
// tooling/profiling surface. Adding one of these to the manifest is a
// deliberate TS API decision, not a parity bug.
const NOT_IN_MANIFEST_ALLOWLIST = new Set([
  'bloom_compile_material_from_file',
  'bloom_profiler_frame_history',
  'bloom_profiler_overlay_text',
  'bloom_set_material_params',
  'bloom_splat_impulse',
  'bloom_set_early_z_enabled',
  // Android host-glue entry points called from the NativeActivity shim,
  // not from Perry:
  'bloom_android_on_touch',
  'bloom_android_set_asset_path',
  'bloom_android_set_native_window',
  // watchOS Swift-host glue (called from BloomWatchApp.swift):
  'bloom_watchos_postfx_state',
  'bloom_watchos_scene_drain_destroyed',
]);

// watchOS intentionally implements a reduced surface; everything else is
// generated as no-op stubs by gen_stubs.js from this same manifest, so
// name presence is checked but a thinner hand-written set is expected.
const STUB_PLATFORMS = new Set(['watchos']);

// ---------------------------------------------------------------------------
// parsing helpers

/** Split a Rust/JSON-ish param list on top-level commas (fn-pointer params
 *  contain nested parens). */
function splitParams(s) {
  const out = [];
  let depth = 0, cur = '';
  for (const c of s) {
    if (c === '(' || c === '<' || c === '[') depth++;
    else if (c === ')' || c === '>' || c === ']') depth--;
    if (c === ',' && depth === 0) { out.push(cur.trim()); cur = ''; }
    else cur += c;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

/** Extract `pub extern "C" fn bloom_*` names + arities from Rust source. */
function extractRustFns(src) {
  const fns = new Map(); // name -> arity
  const re = /pub extern "C" fn (bloom_[a-z0-9_]+)\s*\(/g;
  let m;
  while ((m = re.exec(src)) !== null) {
    // capture to matching close paren
    let depth = 1, i = re.lastIndex, start = i;
    while (i < src.length && depth > 0) {
      if (src[i] === '(') depth++;
      else if (src[i] === ')') depth--;
      i++;
    }
    const params = splitParams(src.slice(start, i - 1)).filter(Boolean);
    // gate-paired definitions (cfg + cfg(not)) share name and arity; keep first
    if (!fns.has(m[1])) fns.set(m[1], params.length);
  }
  return fns;
}

function readDirRust(dir) {
  let all = '';
  for (const f of fs.readdirSync(dir)) {
    if (f.endsWith('.rs')) all += fs.readFileSync(path.join(dir, f), 'utf8') + '\n';
  }
  return all;
}

// ---------------------------------------------------------------------------
// 1. manifest
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const manifest = new Map(); // name -> param count
for (const f of pkg.perry.nativeLibrary.functions) manifest.set(f.name, f.params.length);

// 2. shared macros
const coreSrc = fs.readFileSync(path.join(ROOT, 'native/shared/src/ffi_core.rs'), 'utf8');
const coreFns = extractRustFns(coreSrc);
const physSrc = fs.readFileSync(path.join(ROOT, 'native/shared/src/physics_jolt.rs'), 'utf8');
const physFns = extractRustFns(physSrc);

// 3. platforms
let failures = 0, warnings = 0;
const fail = (msg) => { console.error(`FAIL  ${msg}`); failures++; };
const warn = (msg) => { console.warn(`warn  ${msg}`); warnings++; };

for (const platform of PLATFORMS) {
  const dir = path.join(ROOT, 'native', platform, 'src');
  if (!fs.existsSync(dir)) continue;
  const src = readDirRust(dir);
  const own = extractRustFns(src);
  const usesCore = /define_core_ffi!\s*\(\s*\)/.test(src);
  const usesPhys = /define_physics_ffi!\s*\(\s*\)/.test(src);

  // effective export set
  const effective = new Map(own);
  if (usesCore) {
    for (const [n, a] of coreFns) {
      if (own.has(n)) fail(`${platform}: ${n} hand-written but also generated by define_core_ffi! (duplicate symbol)`);
      effective.set(n, a);
    }
  }
  if (usesPhys) {
    for (const [n, a] of physFns) {
      if (own.has(n)) fail(`${platform}: ${n} hand-written but also generated by define_physics_ffi! (duplicate symbol)`);
      effective.set(n, a);
    }
  }

  // coverage + arity vs manifest
  for (const [name, arity] of manifest) {
    if (!effective.has(name)) {
      fail(`${platform}: manifest function ${name} not exported`);
      continue;
    }
    if (effective.get(name) !== arity) {
      fail(`${platform}: ${name} arity ${effective.get(name)} != manifest ${arity}`);
    }
  }

  // exports not in manifest
  for (const name of effective.keys()) {
    if (!manifest.has(name) && !NOT_IN_MANIFEST_ALLOWLIST.has(name)
        && !name.startsWith('bloom_watchos_')) { // Swift-host glue surface
      warn(`${platform}: exports ${name} which is not in the manifest (unreachable from TS)`);
    }
  }

  const note = STUB_PLATFORMS.has(platform) ? ' (stub platform)' : '';
  console.log(`ok    ${platform}: ${effective.size} exports cover ${manifest.size} manifest functions${note}`);
}

// 4. web (wasm_bindgen + jolt_bridge.js) — name coverage only for now; the
// web crate exposes _str/_bytes variants whose JS glue maps names, so the
// strict check lives with the web FFI work.
{
  const webSrc = readDirRust(path.join(ROOT, 'native/web/src'));
  const names = new Set();
  for (const m of webSrc.matchAll(/pub (?:async )?fn (bloom_[a-z0-9_]+)/g)) names.add(m[1]);
  const bridge = fs.readFileSync(path.join(ROOT, 'native/web/jolt_bridge.js'), 'utf8');
  for (const m of bridge.matchAll(/(bloom_physics_[a-z0-9_]+)\s*[:(=]/g)) names.add(m[1]);
  let missing = 0;
  for (const name of manifest.keys()) {
    // web exposes some functions only as _str/_bytes variants
    if (!names.has(name) && !names.has(name + '_str') && !names.has(name + '_bytes')) missing++;
  }
  if (missing) warn(`web: ${missing} manifest functions have no direct/_str/_bytes export (JS-glue mapped or missing — tightened by the web FFI workstream)`);
  else console.log(`ok    web: full name coverage`);
}

console.log(`\n${failures} failures, ${warnings} warnings`);
process.exit(failures ? 1 : 0);
